# Generated by Django 5.2.6 on 2025-09-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childprofile',
            options={'verbose_name': 'Child Profile', 'verbose_name_plural': 'Kids'},
        ),
    ]
